# Generated by Django 5.0.2 on 2024-05-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distribucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('basada', models.CharField(max_length=100)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
    ]
