# Generated by Django 5.0.2 on 2024-04-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclo',
            name='modulos',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
