# Generated by Django 5.0.2 on 2024-04-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.TextField()),
                ('foto_portada', models.ImageField(blank=True, null=True, upload_to='media/portada_fotos')),
                ('foto_detalle', models.ImageField(blank=True, null=True, upload_to='media/detalle_fotos')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
