# Generated by Django 5.0.2 on 2024-04-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fallout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaje',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
