# Generated by Django 5.0.2 on 2024-04-22 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fallout', '0002_alter_personaje_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaje',
            name='foto_detalle',
            field=models.ImageField(blank=True, null=True, upload_to='fallout/media/detalle_fotos'),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='foto_portada',
            field=models.ImageField(blank=True, null=True, upload_to='fallout/media/portada_fotos'),
        ),
    ]
