# Generated by Django 5.0.2 on 2024-04-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fallout', '0006_alter_personaje_foto_detalle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaje',
            name='foto_detalle',
            field=models.ImageField(blank=True, null=True, upload_to='detalle_fotos'),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='foto_portada',
            field=models.ImageField(blank=True, null=True, upload_to='portada_fotos'),
        ),
    ]
