# Generated by Django 5.0.2 on 2024-04-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('foto_producto', models.ImageField(blank=True, null=True, upload_to='media/productos_fotos')),
                ('descripcion', models.TextField()),
                ('inicio_temporada', models.DateField()),
                ('final_temporada', models.DateField()),
                ('disponible_todo_ano', models.BooleanField(default=False)),
            ],
        ),
    ]
