# Generated by Django 5.0.2 on 2024-05-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='imagen',
            field=models.ImageField(upload_to='memes/media/fotos_memes/'),
        ),
    ]
