# Generated by Django 5.0.2 on 2024-05-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(choices=[('Ferrari', 'FERRARI'), ('Maserati', 'MASERATI'), ('Seat', 'SEAT')], max_length=30)),
                ('modelo', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('nuevo_usado', models.CharField(choices=[('Nuevo', 'NUEVO'), ('Usado', 'USADO')], max_length=6)),
                ('combustible', models.CharField(choices=[('Gasolina', 'GASOLINA'), ('Diesel', 'DIESEL')], max_length=8)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_coches')),
            ],
        ),
    ]
