# Generated by Django 5.0.2 on 2024-05-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coche',
            name='fabricante',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='coche',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='coches/media/fotos_coches'),
        ),
        migrations.AlterField(
            model_name='coche',
            name='nuevo_usado',
            field=models.CharField(choices=[('Nuevo', 'NUEVO'), ('Usado', 'USADO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='coche',
            name='precio',
            field=models.FloatField(),
        ),
    ]
