# Generated by Django 5.0.2 on 2024-06-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coches', '0002_alter_coche_fabricante_alter_coche_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coche',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
