# Generated by Django 5.0.2 on 2024-06-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coches', '0003_coche_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coche',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
